### ISSUE TITLE
Implement two new methods for unit testing of relevance

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-kotlin#101]
- [Specs and CTS tests](https://github.com/algolia/algoliasearch-client-specs-internal/pull/41)
- [Go client base implementation](https://github.com/algolia/algoliasearch-client-go/pull/524)

**Comment by nunomaduro** [comment]
I am re-opening this issue, details here: https://github.com/algolia/algoliasearch-client-specs-internal/issues/45.

**Comment by aseure** [comment]
@q-litzler To give you more precisions:

@nunomaduro rightfully pointed out the following things:

 1. `findFirstObject` should actually be named `findObject`
 2. `findObject` should accept a `paginate = true` optional parameter rather than `doNotPaginate = false`
 3. `getObjectIDPosition` should actually be named `getObjectPosition`

Could you please implement those previous changes? If you already released the previous methods, please introduce the new ones and deprecate the old ones in favor of the newest. However, if you just merged the changes but haven't released them yet, simply rename the methods and their parameters accordingly before your next release.

Thank you in advance and 100% my bad on having not challenged enough the naming of all of this, sorry for the double-work.
