### ISSUE TITLE
New setting: indexLanguages array of strings

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-kotlin#102]
## Summary

Implement the new `indexLanguages` setting which is an array of strings.
Currently, only `["ja"]` is supported by the engine. Changes to be made:

 - Add the setting to the Settings structure/class, if any
 - Set the `indexLanguages` field in the settings integration test if the CTS
   is implemented

## References

 - Specs: https://github.com/algolia/algoliasearch-client-specs-internal/issues/40
 - Go implementation: https://github.com/algolia/algoliasearch-client-go/pull/532

**Comment by aseure** [comment]
@PLNech @q-litzler Could it be possible for you to implement this new setting? Let me know if you have any question regarding the implementation. Thank you very much in advance :)

**Comment by PLNech** [comment]
@aseure added to our backlog! Any deadline? :)

**Comment by aseure** [comment]
@PLNech It's one of our API Clients' OKRs so EOQ / September 30th, implemented and released, but the sooner the better since its a very small change (new array of string setting + one line change in the Common Test Suite). Kotlin is the last missing API client for this feature.

**Comment by q-litzler** [comment]
#110

**Comment by aseure** [comment]
Thanks @q-litzler @PLNech 🙏
