### ISSUE TITLE
Search failed when switch to GZIP encoded

### ISSUE THREAD

**Issue by b95505017** [algolia/algoliasearch-client-kotlin#114]
I use sdk 1.1.2 but get this error:
```
 message: "unrecognized Content-Encoding: gzip"
 status: 415
```

**Comment by q-litzler** [comment]
Hello,

It is possible that your Algolia Application does not support GZIP encoding yet.
If that's the case, please do not use the option `Compression.Gzip`.

**Comment by b95505017** [comment]
@q-litzler Hi, how do I verify it?

**Comment by q-litzler** [comment]
If you had this error, it means that it is not activated for your Algolia Application

**Comment by b95505017** [comment]
@q-litzler How do I activate it?

**Comment by q-litzler** [comment]
As this is a question related to Algolia infrastructure, please contact Algolia support directly. You can reference this issue in your query.
