### ISSUE TITLE
NoClassDefFoundError with encoding base64 in generateAPIKey

### ISSUE THREAD

**Issue by b95505017** [algolia/algoliasearch-client-kotlin#129]
```
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/util/Base64;
com.algolia.search.helper.HashingKt.encodeBase64 (HashingKt.java:21)
```

It should use `android.util.Base64` in Android.

**Comment by q-litzler** [comment]
To fix this problem, we would need to add an Android target that would use `android.util.Base64` in the `actual` declaration of the method.

(This requires the same work as #74)

I'll let you know when this is done, I sadly can't give any ETA at the moment.

**Comment by q-litzler** [comment]
Hello, the android target is now available.

The artifact is `com.algolia:algoliasearch-client-kotlin-android:1.2.0-beta01`

Please try it and let me know if this resolve your issue.

**Comment by b95505017** [comment]
Do I need to exclude `algoliasearch-client-kotlin-jvm` when applying `instantsearch-android` when switch to `algoliasearch-client-kotlin-android`?

**Comment by q-litzler** [comment]
If you are a InstantSearch user, put only this line in your `build.gradle` file:

`com.algolia:instantsearch-android:2.2.0-beta01`

It will automatically include the client `com.algolia:algoliasearch-client-kotlin-android:1.2.0-beta01`.

**Comment by q-litzler** [comment]
Did it solve your problem @b95505017 ?

**Comment by b95505017** [comment]
ok thanks!
