### ISSUE TITLE
Documentatioin

### ISSUE THREAD

**Issue by danielgomezrico** [algolia/algoliasearch-client-kotlin#139]
# Current

No documentation about how to setup a new client

I just see put "this on gradle" 

```
   implementation "io.ktor:ktor-client-android:$ktor_version"
```

# Expected

Some kind of text explaining that like:

> "You just need to put this gradle depe ndency and the library will configure automatically to use the client"

Also what is the ktor version I should use?

**Comment by q-litzler** [comment]
Thank you for your feedback.

> Also what is the ktor version I should use

Ktor `1.2.4`, for the library version `1.1.4`. New versions might upgrade this dependency, this will be indicated in the release notes.

> No documentation about how to setup a new client

There's a Getting Started guide right [here](https://github.com/algolia/algoliasearch-client-kotlin/blob/master/docs/GettingStarted.md). And a full documentation on Algolia's [website](https://www.algolia.com/doc/api-client/getting-started/install/kotlin/?language=kotlin).
