### ISSUE TITLE
Please help upgrade to Ktor 1.3.x

### ISSUE THREAD

**Issue by b95505017** [algolia/algoliasearch-client-kotlin#157]
https://github.com/ktorio/ktor/releases/tag/1.3.0

**Comment by spinach** [comment]
Hello,

You can try Algolia version [1.3.0-beta01](https://bintray.com/algolia/maven/algoliasearch-client-kotlin/1.3.0-beta01) to test it out. 

Thanks!

**Comment by b95505017** [comment]
It says `ERROR: Failed to resolve: com.algolia:algoliasearch-client-kotlin-jvm:1.3.0-beta01
`
Not sure causing by lacks some pom file sort of.
https://dl.bintray.com/algolia/maven/com/algolia/algoliasearch-client-kotlin-jvm/1.3.0-beta01/

**Comment by spinach** [comment]
Hello @b95505017 ,

You are right, there was a bug when uploading the beta version. we'll fix this and deploy a new version, thanks a lot for your patience.

You can temporarily use the idea behind this [thread](https://stackoverflow.com/questions/18748436/is-it-possible-to-declare-git-repository-as-dependency-in-android-gradle) to point to the `fix/ktor-1.3` branch in this repo in case you are in a rush.

**Comment by spinach** [comment]
Hello,

I just released `1.3.1` since 1.3.0 was corrupted. You can try it out. Thank you for your patience!
