### ISSUE TITLE
Support Kotlin 1.3.70 & Kotlinx serialization 0.20.0

### ISSUE THREAD

**Issue by b95505017** [algolia/algoliasearch-client-kotlin#160]
[Kotlinx serialization 0.20.0 release note](https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#0200--2020-03-04)

**Comment by spinach** [comment]
Hello @b95505017 - It seems that Kotlinx serialization has just been released, and there are some issues that are popping up and marked as bugs in [their repo](https://github.com/Kotlin/kotlinx.serialization/issues?q=is%3Aopen+is%3Aissue). We're waiting for it to stabilise before upgrading.

**Comment by b95505017** [comment]
@spinach There are more and more libraries use kotlin 1.3.70/1.3.71 now, is it possible to release a beta version?

**Comment by Aallam** [comment]
A new beta version `1.4.0-beta01` has been released! 🎉

**Comment by b95505017** [comment]
@Aallam I'll test it right now. Thanks a lot!
