### ISSUE TITLE
Support the double quotes for the Filter.Facet

### ISSUE THREAD

**Issue by PhilippeBoisney** [algolia/algoliasearch-client-kotlin#182]
**Is your feature request related to a problem? Please describe 🙏**  
When I build a `Filter.Facet` and pass to the `value` field a `String` containing a double quote(`"`), this one is misinterpreted (and incorrectly serialized).

For example:
```
val notSupportedValue = "24" and more"
Filter.Facet(Attribute("screen_size"), value = notSupportedValue)
```
This case will throw an exception by the HTTP Client of the SDK:
`HttpClient: {"message":"filters: Not allowed incomplete string at col 114", "status":400}`

**Describe the solution you'd like 🤔**  
As a **quick fix**, I "format" each facet value before sending them to the SDK:
```
/**
 * Formats the receiver [String] in order to add some escape characters.
 * For example:
 *  - 24" and more => 24\" and more
 */
private fun String.formatForJson() =
    replace("\"", "\\\"")
```

**Describe alternatives you've considered ✨**  
When passing any `String` to the `Filter.Facet` constructor, make sure to handle/add when necessary an escape character.

**Comment by spinach** [comment]
Hi @PhilippeBoisney ,

Thank you for submitting this issue.

Concerning double quotes, we ask you to handle it yourself as you pointed out in your solution. This is mentioned in our official docs, under [Handle Attributes with Double Quotes](https://www.algolia.com/doc/api-reference/api-parameters/filters/#handle-attributes-with-double-quotes).

Thanks!

**Comment by PhilippeBoisney** [comment]
Hi @spinach! 
Thanks for your feedback. However, I don't understand why the double quotes **are supported by the iOS SDK** and not by the Android (Kotlin) one.

Is there any reason for that? 🙂

**Comment by spinach** [comment]
Hey @PhilippeBoisney ,

That's a good feedback, I will report this to the team, as the behaviour should be consistent in both platforms (as well as the doc). Sorry about this, and feel free to use the solution you described, as it should solve your problem 🙂 

Thanks again!

**Comment by ArvindSenDecathlon** [comment]
This hack is not working in our project. Can you please help with this when I select filter 8-9 years/4'3"-5'6", it gives an error.
