### ISSUE TITLE
Ensure consequence.params.ignorePlurals can be deserialized from string

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-kotlin#197]
It was discovered that the Algolia Search API is sometimes returning the
`ignorePlurals` field from a Query Rule's consequence params field as a
string, such as:

```json
"consequence": {
    "params:" {
        "ignorePlurals": "false"
    }
}
```

Could you please ensure that the deserialization of query rules coming from
`getRule`, `getRules`, `browseRules` are correctly decoding those strings
without failing.

Also, like we did for other string-based booleans, it would be convenient to
convert the string to an actual boolean when the string is equal to "true" or
"false".

**Comment by Aallam** [comment]
Kotlin Client has an [IgnorePlurals](https://github.com/algolia/algoliasearch-client-kotlin/blob/3947e2c65abf84023f0a25771ccd5e35155191dd/src/commonMain/kotlin/com/algolia/search/model/search/IgnorePlurals.kt) class that [handles](https://github.com/algolia/algoliasearch-client-kotlin/blob/3947e2c65abf84023f0a25771ccd5e35155191dd/src/commonMain/kotlin/com/algolia/search/model/search/IgnorePlurals.kt#L56) correctly this issue.
