### ISSUE TITLE
android parcelable support for model class

### ISSUE THREAD

**Issue by phm1015** [algolia/algoliasearch-client-kotlin#198]
I am having difficulty passing algolia model class which is serializable between UI components.
 for ex. (fragments, activities)
some how i can pass model class between fragments but i cannot pass model class as parcelable.
Also i am not sure how to pass algolia model class between activities.

I am able to make my model class parcelable but my model class also have already available "ranking_info, ObjectID, "highlight_result" class from lib. as fields which are not parcelable.So its causing the issue

Is there any way i can pass data between UI components.

If not can you please add parcelable support for model class?

**Comment by Aallam** [comment]
A general rule of thumb is to always limit the data passed between UI components to the very strict minimum. 

Parcellable is not the only way to do this if it does not work for you, all depend on your use case, here are some of many possible ways of doing this:
* If your data backed by a database it might be enough to just pass in the ID, then load them.
* Use parent activity to share data.
* [Shared ViewModel](https://blog.mindorks.com/shared-viewmodel-in-android-shared-between-fragments)
* Dependency injection
* [FragmentManager](https://developer.android.com/training/basics/fragments/pass-data-between)

If there is a request that Algolia can help with, feel free to re-open an issue

**Comment by phm1015** [comment]
lets say i want to pass serializable model class between two activities then how will i achieve that?
 suppose one activity shows search list and if i click on any list item how will i pass that algolia object to another activity?

**Comment by Aallam** [comment]
Hello @phm1015,
Here is a simple [example](https://github.com/algolia/instantsearch-android-examples/compare/sample/activityArg) showing one of many possible ways to do this.
