### ISSUE TITLE
Need 1.5.0-beta01 artifact for algoliasearch-client-kotlin-android

### ISSUE THREAD

**Issue by b95505017** [algolia/algoliasearch-client-kotlin#216]
Currently 1.5.0-beta01 only released with JVM but Android, which can't find java.util.Base64 before Android 8.

**Comment by Aallam** [comment]
Hello @b95505017, thank you for reporting this.
The best approach here is to remove the `java.util.Base64` and replace it with another implementation. It's an overkill to create a whole artifact only for this.

**Comment by b95505017** [comment]
@Aallam How to I change the Base64 implementation with `generateSecuredAPIKey` function?

**Comment by Aallam** [comment]
@b95505017, I've created a PR for this, we should be able to merge this quickly

**Comment by b95505017** [comment]
So quick! Thanks a lot!
