### ISSUE TITLE
Rename `replaceExistingSynonyms` to `clearExistingSynonyms`

### ISSUE THREAD

**Issue by chloelbn** [algolia/algoliasearch-client-kotlin#234]
The parameter `replaceExistingSynonyms` in the `saveSynonyms` method is inconsistent with the rest of our API. We should rename it to `clearExistingSynonyms`. Backward-compatibility should be kept in mind

**Comment by Aallam** [comment]
In Kotlin client, the parameter has the correct name.
https://github.com/algolia/algoliasearch-client-kotlin/blob/9ca03914bf6f1a14bbb64823498b61a909fb5c9d/src/commonMain/kotlin/com/algolia/search/endpoint/EndpointSynonym.kt#L61
