### ISSUE TITLE
Error turning ResponseSearch into String

### ISSUE THREAD

**Issue by hugomarcelino-spotqa** [algolia/algoliasearch-client-kotlin#283]
Hey Algolia,

I'm integrating Algolia with our product and came across what I believe to be a bug. We are using the Algolia Kotlin client to make our queries. 

Our request flow is similar to this:
```
Gradle app:

Browser -> module:web / java 
               -> dependency: module: Algolia / kotlin => this is the one that makes the request to Algolia
```

The problem occurs when returning the response to the browser.

```java
Caused by: java.lang.NullPointerException
	at com.algolia.search.model.response.ResponseSearch.getLength(ResponseSearch.kt:262)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	... 76 more
```

The problem relies on the way `ResponseSearch.kt` is built. You're defining that a property can be null but then on the getter you're saying that it will never be null.

```kotlin

ResponseSearch(
...
@SerialName(KeyLength) val lengthOrNull: Int? = null,
...

// and then on the getter you do:

public val length: Int
     get() = lengthOrNull!! // <-- This is wrong. lengthOrNull can be null as the name implies

```

The way this is built makes it impossible to use `ResponseSearch.kt` to make business decisions.

Considerations:
* Kotlin version: 1.5.30
* Algolia Kotlin client: 1.9.2
* I'm making a multi-index query

**Comment by hugomarcelino-spotqa** [comment]
I was able to solve the NPE in the `length` by providing `length` and `offset` in the queries but then I got another error in the property `message`.

**Comment by Aallam** [comment]
Hi @hugomarcelino-spotqa, thank you for filling the issue. Is it possible for your use case to use `lengthOrNull` instead of `length`?

**Comment by hugomarcelino-spotqa** [comment]
Yes, it is possible. Another problem is if you're using a different json serializer, like Jackson, he will call the function instead of the property and that will cause NPE. 

For my current situation the `lengthOrNull` works.

**Comment by Aallam** [comment]
> Yes, it is possible. Another problem is if you're using a different json serializer, like Jackson, he will call the function instead of the property and that will cause NPE.

It should not serialize properties not backed by a field. A workaround can be using a custom Jackson serializer. 

> For my current situation the `lengthOrNull` works. 

Glad to hear it!

**Comment by hugomarcelino-spotqa** [comment]
Not to prolong this but in `ResponseSearch`, `length` is a field. Because you have defined `get()` for this field, when requesting the value of the field, Kotlin will implicitly call the `get()`.  The only solution for this would be to tell Jackson to ignore this field.

Closing this issue since I have found a way to work around the problem.
