### ISSUE TITLE
Recommend client

### ISSUE THREAD

**Issue by DevinCodes** [algolia/algoliasearch-client-kotlin#289]
We need to add a new client to interact with the [Recommend](https://www.algolia.com/doc/rest-api/recommend/#get-recommendations) API. The API and implementation can be based on the [JavaScript client](https://github.com/algolia/algoliasearch-client-javascript/pull/1280).

**Comment by Aallam** [comment]
[Implemented](https://github.com/algolia/algoliasearch-client-kotlin/pull/281) and released in version [1.10.0](https://github.com/algolia/algoliasearch-client-kotlin/releases/tag/1.10.0)

**Comment by DevinCodes** [comment]
Thank you!
