### ISSUE TITLE
NoClassDefFoundError - Ktor

### ISSUE THREAD

**Issue by ptsiogas** [algolia/algoliasearch-client-kotlin#367]
Hi, we are using KMM in our product. We have integrated the
`implementation platform('com.algolia:algoliasearch-client-kotlin-bom:2.1.0')`
in android application gradle level.

The project is building OK but when we are getting the crash below in runtime.

`java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/network/sockets/SocketTimeoutException;`

We are using the dependencies below in our KMM module gradle:
```
val ktorVersion = "1.6.7"
val commonMain by getting {
    dependencies {
        ...
        implementation("io.ktor:ktor-client-core:$ktorVersion")
        implementation("io.ktor:ktor-client-serialization:$ktorVersion")
        implementation("io.ktor:ktor-client-logging:$ktorVersion")
    }
}
val androidMain by getting {
    dependencies {
        ...
        implementation("io.ktor:ktor-client-android:$ktorVersion")
        implementation("io.ktor:ktor-client-okhttp:$ktorVersion")
    }
}
```

I suppose there is a dependency between the ktor version we are using and the algolia's ktor version. Can you assist in order to find a solution?

**Comment by ptsiogas** [comment]
> Hello @ptsiogas,
> 
> I think you got the error because Algolia Kotlin API client 2.x depends on Ktor client 2.x. In the gradle dependencies you shared, you are using version `1.6.7`, which doesn't have the class `io.ktor.client.network.sockets.SocketTimeoutException`.

We are currently using SocketTimeoutException with Ktor 1.6.7 without any issue. The crash happens only when we add the algolia dependency. I am afraid that using a Ktor client 2.x.x is a prerequisite for using the algolia kotlin sdk. You should mention that in the readme section.

**Comment by Aallam** [comment]
> We are currently using SocketTimeoutException with Ktor 1.6.7 without any issue

The class `io.ktor.client.network.sockets.SocketTimeoutException` does not exist in Ktor 1.6.7, what you are using is `io.ktor.network.sockets.SocketTimeoutException`. The class package changed between Ktor client 1.x and 2.x. 

> I am afraid that using a Ktor client 2.x.x is a prerequisite for using the algolia kotlin sdk

To use the latest version of the Kotlin API client, yes.  
Although I don't recommend using older versions, Kotlin client 1.x however depends on Ktor 1.x.

>  You should mention that in the readme section.

Thank you for your feedback.   
Please be aware this dependency is mentioned in the [changelog](https://github.com/algolia/algoliasearch-client-kotlin/blob/master/CHANGELOG.md#200).

**Comment by ptsiogas** [comment]
Thanks @Aallam . The real question here is: should all kotlin libraries use the same ktor version?
I suppose that this should not be a prerequisite. Do you know a way in order to use the latest Algolia-kotlin client and keep the existing ktor version 1.6.7 of my project?

**Comment by Aallam** [comment]
> The real question here is: should all kotlin libraries use the same ktor version?

This question is related to how [Gradle version conflict resolution](https://docs.gradle.org/current/userguide/dependency_management.html#sec:version-conflict) works, Gradle selects **one** version corresponding to the highest version by default, and offers an API to customize the resolution strategy.
