### ISSUE TITLE
Add: IndexSettings -> userData

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-kotlin#62]
`UserData` is now a property of `IndexSettings`. It's a schema less `object` defined by the user.

For more information see [C# PR](https://github.com/algolia/algoliasearch-client-csharp/pull/603).

**Comment by q-litzler** [comment]
https://github.com/algolia/algoliasearch-client-kotlin/pull/69

**Comment by aseure** [comment]
Re-opening to make sure the CTS test is implemented in the same way across all our clients (see https://github.com/algolia/algoliasearch-client-specs-internal/pull/38).

**Comment by q-litzler** [comment]
#143
