### ISSUE TITLE
Add -> primary parameter in IndexSettings

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-kotlin#64]
The `primary` parameter keeps track of which primary index (if any) a replica is connected to.

Type: `String`
**Only getable**  on the `IndexSettings` of a replica.

**Comment by q-litzler** [comment]
https://github.com/algolia/algoliasearch-client-kotlin/pull/69

**Comment by aseure** [comment]
Re-opening to make sure the CTS test is implemented in the same way across all our clients (see https://github.com/algolia/algoliasearch-client-specs-internal/pull/38).

**Comment by q-litzler** [comment]
This parameter is not present in the list of parameters to test in the CTS for Settings

https://github.com/algolia/algoliasearch-client-specs-internal/blob/master/common-test-suite/README.md#settings

**Comment by aseure** [comment]
Really sorry, I've reopened this issue wrongly. Sorry for the noise @q-litzler
