### ISSUE TITLE
Add support for iOS

### ISSUE THREAD

**Issue by Ribesg** [algolia/algoliasearch-client-kotlin#73]
Hi,

We at Wizbii have been using a custom client implementing the Algolia REST API in a multiplatform context for some time now. It "supports" the JVM, Android and iOS, but is very barebone and lacks most Algolia features. We implemented the bare minimum we needed.

We would like to migrate to the official Kotlin client, but for that we need it to support the different iOS platforms (arm64 and x86_64, arm32 would probably be nice too).

Here are two Gists demonstrating iOS build in multiplatform: https://gist.github.com/Ribesg/95a172ceb2177d74cf5b15993d40092e

Thanks

**Comment by spinach** [comment]
Hello, 

We're very sorry for the late reply here, we should have given an update earlier.

We understand the demand for adding native support, and hopefully we'll be able to add support for this in the near future, however, this is not our priority right now, and the demand is not high enough to justify the high cost of implementing this. So on our side, we added it on our backlog and hopefully we'll have the time to tackle this sometime soon

I hope you understand and thank you for the feature request!
