### ISSUE TITLE
Add Android target

### ISSUE THREAD

**Issue by Ribesg** [algolia/algoliasearch-client-kotlin#74]
Simple Android apps can currently import and use the `jvm` version of the library, but in a multiplatform context, it's easier to just import the "root" library and let the multiplatform plugin use the gradle metadata to import all needed target.

During this process, the plugin will look for `android` and/or `android-debug` targets, and not `jvm`. That's why android releases are required.

**Comment by q-litzler** [comment]
Hello, the android target is now available.

The artifact is `com.algolia:algoliasearch-client-kotlin-android:1.2.0-beta01`

PR #132
