### ISSUE TITLE
Check automaticRadius type in search response is string

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-kotlin#91]
A user of the Go client [reported](https://github.com/algolia/algoliasearch-client-go/issues/518)
on support that they had issue while the Go client was deserializing the
`automaticRadius` field of a geo search query.

The [Algolia documentation says](https://www.algolia.com/doc/api-reference/api-methods/search/?language=go#method-response-automaticradius)
the type of `automaticRadius` is a string but, as of today, the written type
annotation is marked to float.

Let's make sure that this field is correctly typed as a string (and not a
float), as it should.

For the record, to make `automaticRadius` in a search response, you need to
perform a search query with:

 - with a geo parameter such as `aroundLatLng`
 - without any `aroundRadius` search parameter
 - have records in your index that will match the geo query, so they need to
   have a `_geoloc` attribute

**Comment by PLNech** [comment]
Hi @aseure, thanks for the report. Indeeed we have `automaticRadius` typed as `Float` too, I'll send a PR changing that!

**Comment by PLNech** [comment]
Wait I'm confused: the docs say
> `float` The automatically computed radius. For legacy reasons, this parameter is a **string** and not an **integer**.  Only returned for geo queries without an explicitly specified radius (see aroundRadius).

Trusting your top comment as the source of truth, I guess this means the docs are wrong and should read "`string` | ... a string and not a _float_". 

@aseure can you confirm before I start implementing the change? :thinking:

**Comment by aseure** [comment]
Yes docs are wrong, I'm submitting a PR to the doc right now to make it explicit that it's a `string` 💯 (which represents a floating-point number).

**Comment by aseure** [comment]
Documentation PR: https://github.com/algolia/doc/pull/3447
